### ISSUE TITLE
Add Lurie Childrens Hospital as a Data Provider group.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/commons#106]

**Comment by yuanzhou** [comment]
Update all the APIs to use the latest commons 2.1.6 and rebuild on DEV and TEST before release:

- [ ] entity-api
- [ ] gateway
- [ ] search-adaptor and search-api
- [ ] uuid-api
- [ ] ingest-api

Will also need to upload a new dependecy zip file for the AWS Lambda authorizers.
