### ISSUE TITLE
New groups and expose `description` field via `get_globus_groups_info()`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/commons#128]
Two things:

- Add new globus group to [21f293b0-globus-groups.json](https://github.com/hubmapconsortium/commons/blob/main/hubmap_commons/21f293b0-globus-groups.json)- for HuBMAP-Workspaces-Beta
- Add `description` field to the `get_globus_groups_info()` method so Harvard team no longer needs to parse the json file

This is per: [Slack message in #portal-deployment channel from Lisa Choy](https://hubmapconsortium.slack.com/archives/C016TK0APV2/p1717162976456059?thread_ts=1716494617.978669&cid=C016TK0APV2)

Will notify the Harvard team once it's released.

**Comment by shirey** [comment]
@DerekFurstPitt 

Info for Workspaces Group:
  name: HuBMAP-Workspaces-Beta
  uuid: fb09d4dd-da04-11ed-b5f2-b5fe535477fb
  description: This group will be used to maintain a list of users with access to the Beta phase of the Workspaces release.
  displayname: Workspaces Beta
