### ISSUE TITLE
Dependency error when using commons as a dependency of another project

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/commons#7]
The commons package is being used by entity-api, uuid-api, ingest-ui, gateway and some other projects as a dependency. When the project also uses python requests (say 2.22.0) as another dependency, the installation throws an error:

````
ERROR: hubmap-commons 0.0.1 has requirement requests==1.2, but you'll have requests 2.22.0 which is incompatible.
````

Not sure if this would really cause any issues.

**Comment by cborromeo** [comment]
@yuanzhou how do I trigger the error?  Is there a certain build command that causes this?  I need something to test to ensure I fixed it.

**Comment by yuanzhou** [comment]
@cborromeo I closed this issue since Julian has updated the requests version, but it came up another build error and I think he'll work on that. Sorry for the confusion.
