### ISSUE TITLE
Pass "group mapping" json file on auth helper instantiation

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/commons#85]
Currently we use hubmap-globus-groups.json for Globus group mapping information- default the instantiation of any helper classes (like hm_auth, maybe the only one??) to use this file, but if an optional parameter specifying this is provide use that instead.

**Comment by maxsibilla** [comment]
This is supported in commons in [test-release ](https://github.com/hubmapconsortium/commons/blob/b9ec9cd55db67f08a71b5cae0b6a6bceb80b49f5/hubmap_commons/hm_auth.py#L131). A PR in dev-integrate in the UUID-API takes advantage of this by allowing a user to pass a globus-groups json file when instantiating hm_auth.
